/**
 * The paper the chapters are printed on.
 *
 * One tile of contour lines — level sets of a stream function, generated by
 * `scripts/gen-wave-texture.mjs` and exactly seamless in both axes — repeated
 * behind a section's content. It is Chapter .01's field spent as texture: the
 * hero draws the fluid, everything below it sits on the impression the fluid
 * left.
 *
 * Painted as a **mask**, not as an image. The SVG is white on transparent and
 * the stylesheet pushes `currentColor` through it, so a single 39kB file is
 * acid ink on the void, void ink on Chapter .05's acid, and void ink on
 * Chapter .02's slab, with no second asset and no filter hacks. That is also
 * why colour is set on this element rather than baked into the file — a
 * section says what colour its paper is by saying `text-…`.
 *
 * `z-0` and `aria-hidden`: it is the bottom of its section's stacking context
 * and nothing else. Every section that mounts it keeps its content in a
 * `relative` wrapper, which is what puts the type above the paper — an
 * absolutely positioned sibling otherwise paints over static content.
 */
export default function SiteTexture({
  className,
}: {
  /** Ink colour and strength — e.g. `text-acid opacity-[0.16]`. */
  className?: string;
}) {
  return (
    <div
      aria-hidden
      data-texture
      className={`pointer-events-none absolute inset-0 z-0 ${className ?? ""}`}
    />
  );
}
